### ISSUE TITLE
Would you like to make this a Flutter Bounty Hunters project?

### ISSUE THREAD

**Issue by matthew-carroll** [krokyze/flutter_seo#11]
Hi, I came across this package and it seems like an interesting direction for search indexing of Flutter webpages.

At the Flutter Bounty Hunters, we've been working on document editors and renderers in Super Editor. We also build our webpages with Flutter for web. This project looks like it would make sense within that ecosystem.

If you'd like to chat about migrating this project into our portfolio, and then working on getting funding for it, please let me know. You can respond here, or send me a [DM on twitter](https://twitter.com/suprdeclarative), or message me at https://flutterbountyhunters.com

**Comment by krokyze** [comment]
Hey. I'll send you message.
