### ISSUE TITLE
Usage with other packages

### ISSUE THREAD

**Issue by chrisbinsunny** [krokyze/flutter_seo#15]
The SEO package could be integrated very well with inbuilt widgets in flutter. But when it comes to third-party packages such as [AnimatedText](https://pub.dev/packages/animated_text_kit), it is not the case. There is no way to integrate the SEO package with packages. Are there any upcoming releases or workaround for this one?

**Comment by krokyze** [comment]
The package isn't connected with any inbuilt widgets, you can wrap within `Seo.text(...)` anything you need. For example for AnimatedText you can do this:

```
Seo.text(
  text: 'AWESOME OPTIMISTIC DIFFERENT',
  child: AnimatedTextKit(
    animatedTexts: [
      RotateAnimatedText('AWESOME'),
      RotateAnimatedText('OPTIMISTIC'),
      RotateAnimatedText('DIFFERENT'),
    ],
  ),
);
```
