### ISSUE TITLE
Style of text should affect the HTML tag

### ISSUE THREAD

**Issue by guplem** [krokyze/flutter_seo#16]
It is probably a good idea to relate a specific HTML tags to specific flutter text styles, so when the HTML gets built, the headline1 uses `<h1>`, headline2 `<h2>`, … and for the standard text (body2) `<p>`.  Here you have [the list of the styles](https://api.flutter.dev/flutter/material/TextTheme-class.html),

I do believe that those tags are used by the search engines to categorize the content.

[This package](https://pub.dev/packages/flutter_web_seo#usage) uses a different but similar approach. I wouldn't like to have 2 packages (one for images + links and another for text…)

**Comment by krokyze** [comment]
I agree that's a must have. I'll look into adding support for this in the next release, I just need to find time for that 😉

**Comment by krokyze** [comment]
Support for h1-h6 tags has been released in version `0.0.4`.
