### ISSUE TITLE
Option to prerender html tags during build time

### ISSUE THREAD

**Issue by razfazz** [krokyze/flutter_seo#19]
first. thank you for providing this package and working on that. it could be a gamechanger and open a totally new field for flutter web.

I am not sure if it is possible but it would likely increase indexability and SEO score a lot if it would be possible to prerender the flt-seo tags during build time. maybe with a command like this. 

`flutter build web --web-renderer seo-htmlkit`

**Comment by krokyze** [comment]
Sorry but that's just impossible. It kinda could be possible for static content webpage but for dynamic loaded content one there's no way to prerender anything.

**Comment by razfazz** [comment]
wow that was a fast response!
yes I am talking about a usecase where someone wants to use his design skills in flutter to build a static webpage with no dynamic content.

**Comment by krokyze** [comment]
In that case I would strongly advise creating regular html web app as supporting something like prerendering for a static content webpage still requires a lot of custom work, changes and to be honest I'm not even sure it would even work.
