### ISSUE TITLE
Facebook og:image meta property

### ISSUE THREAD

**Issue by arindammitra06** [krokyze/flutter_seo#22]
Hi There, Thanks for the awesome package. I am trying to use the library in a web project of mine which does sharing of images. I tries to use the Seo.head() function to add meta tags to the <head> and I can see the tags in my DOM, but the facebook crawler is unable to find them because it just sees my index.html before rendering. Any idea how this can be solved? 

The way I added the meta tags. Thanks again for your help.

`Seo.head(
                tags: [
                  MetaTag(name: 'og:image', content: currentFeed!.imageUrl, ),
                  MetaTag(name: 'title', content: currentFeed!.content, ),
                  MetaTag(name: 'og:title', content: currentFeed!.content, ),
                  MetaTag(name: 'og:description', content: description,),
                  MetaTag(name: 'og:url', content: url,),
                  MetaTag(name: 'og:type', content: 'article',),
                  LinkTag(rel: 'canonical', href: url),
                ],
child: ....`

**Comment by krokyze** [comment]
Hey.

Sorry but that's impossible, as I did mention it right below https://github.com/krokyze/flutter_seo#head:

> **WARNING**: Open Graph (og:title, og:description, etc.) and Twitter Card (twitter:title, twitter:description, etc.) will not work. [Read more](https://github.com/krokyze/flutter_seo#supporting-open-graph-twitter-card-tags).

**Comment by arindammitra06** [comment]
Thank You.
