### ISSUE TITLE
Cross platform use

### ISSUE THREAD

**Issue by polarby** [krokyze/flutter_seo#28]
This may not only be plugin related, but having a cross platform app (android, iOS, and web) importing this plugin is impossible, as `html` plugin is not supported on mobile.

@krokyze Are there any options that you have come across to target such a situation? How to use SEO for web for an app targeted for more than just web?

**Comment by krokyze** [comment]
There shouldn't be any issues with cross platform as long as you import only `import 'package:seo/seo.dart';` as you can see https://github.com/krokyze/flutter_seo/blob/main/lib/seo.dart it does have different imports for specific plaforms.

**Comment by polarby** [comment]
True that works! Great thanks!

It's weird though that the other paths are exposed for client import. Is that on purpose? When auto-importing (via android studio) it will NOT import `seo.dart` but each file individually (`import 'package:seo/html/seo_controller.dart'`) - in my case the html controller.
Is it possible to exclusively force import `package:seo/seo.dart` and thus ensure proper platform selection?
