### ISSUE TITLE
Does this package working?

### ISSUE THREAD

**Issue by MrShailandra** [krokyze/flutter_seo#31]
Hi, I have recently come across this package and went to integrate it into my project. I have tried to do Google Crawl Test on an example website. but Crawl is not able to get any h1,h2 as well alt tags.  I'm using this website for testing -> https://totheweb.com/learning_center/tools-search-engine-simulator/

Can you please check it?

**Comment by krokyze** [comment]
Hey. My only guess is that most of these online "SEO validator" tools does not support running JavaScript while [Googlebot does support it](https://developers.google.com/search/blog/2019/05/the-new-evergreen-googlebot)

All these are H6 tags in my example project: <img src="https://puu.sh/JKDRZ/c45f51cb9f.png" />
