### ISSUE TITLE
Seobility doesn't see tags and content

### ISSUE THREAD

**Issue by kfranic1** [krokyze/flutter_seo#37]
I'm using Seobility to check my SEO score for flutter webapp and I get the following errors
![image](https://github.com/krokyze/flutter_seo/assets/56261743/bdf5f317-ca87-4aa0-bab5-5601988dad2c)
![image](https://github.com/krokyze/flutter_seo/assets/56261743/a924509f-abf4-444f-91f4-b38ea4cdfb46)
![image](https://github.com/krokyze/flutter_seo/assets/56261743/0ab88759-316b-46c7-bf89-8181d1adf3a6)

As you can see in the following image my webapp does have `h1`, `h2`, `links` and, `p` tags

![image](https://github.com/krokyze/flutter_seo/assets/56261743/3c87afb4-ef50-4ea5-a1e9-346d1bb145ff)

I'm not sure if this is a problem for SEO in general.

EDIT: Your example page has the same errors

**Comment by krokyze** [comment]
Hi.

I cannot say for 100% percent but I do think it's related to this: https://github.com/krokyze/flutter_seo/issues/31#issuecomment-1620787118

**Comment by kfranic1** [comment]
Thanks for replying, hopefully than the SEO will be fine
