### ISSUE TITLE
HTML Script creates error in console

### ISSUE THREAD

**Issue by loic-hamdi** [krokyze/flutter_seo#40]
Adding this code:
```html
<script>
  if (bot) {
    window.flutterWebRenderer = "html";
  }
</script>
```

Creates this console error:
`ReferenceError: Can't find variable: bot`

**Comment by krokyze** [comment]
That's just short example, the full example is below the url:

> To improve initial page load speed for bots you can force HTML renderer which is 2MB smaller in download size than CanvasKit. Full example [here](https://github.com/krokyze/flutter_seo/blob/main/example/web/index.html#L20..L29).
> ```html
> <script>
>   if (bot) {
>     window.flutterWebRenderer = "html";
>   }
> </script>
> ```
