### ISSUE TITLE
seo text gets displayed on the splash screen 

### ISSUE THREAD

**Issue by opheliagame** [krokyze/flutter_seo#41]
Since the style of tags are using black color, the text gets displayed on the splash screen. Is there any specific need to make the text black?

**Comment by krokyze** [comment]
Would you mind providing a screenshot, please?

**Comment by opheliagame** [comment]
I cannot share what I am working on currently since it is not open source :(( 
but you should be able to reproduce it with a splash screen image that is not full height. So that when the screen is displaying the image, the seo text is visible in the back in black color. 

There are workarounds having a full height div behind your splash screen image but I started this issue since I was wondering if there is any reason for having black color set in the style of each tag that gets added. 
https://github.com/krokyze/flutter_seo/blob/ee37541b84b7202db82152e9c26c1d2e48664b35/lib/src/seo_tree.dart#L37

**Comment by krokyze** [comment]
To be honest in my experience I've never had issues, with the text being visible as the flutter canvas view has it's own background which overlays the black text. Without an example It's quite hard for me to understand the situation.

The reason why I chose black color was more like a guess that google bot might see white text on white background as a bad practice.
