### ISSUE TITLE
Google search returning untitled

### ISSUE THREAD

**Issue by Dassine** [krokyze/flutter_seo#43]
Hi there, 

I integrated this package and used seo.head() to add my title, description, author and keywords. I see them in the google search (url inspection). I'm not sure why Google Search is not displaying them. 

Thanks for your help!

**Comment by krokyze** [comment]
Hey.

It takes a while for page to appear in Google Search, is it appearing now?

**Comment by Dassine** [comment]
Hey! Thank you for your answer. it's been already 3 months :(

**Comment by krokyze** [comment]
Could you share your website url?

**Comment by nokia6290** [comment]
any news?

**Comment by krokyze** [comment]
For now Google has indexed 3 of my example pages.

![Screenshot 2024-07-26 at 01 01 43](https://github.com/user-attachments/assets/31eb6c17-5c21-42da-b66b-beb10f30e9f7)
