### ISSUE TITLE
html text get displayed on screen

### ISSUE THREAD

**Issue by tonylam1015** [krokyze/flutter_seo#45]
Hello,

I have just updated flutter framework to the latest 3.16.2 and discovered that the html texts get displayed on the screen.

![image](https://github.com/krokyze/flutter_seo/assets/152942222/61f61ef9-2289-495a-b854-ef270ffceeb0)

Here is the code:

Widget build(BuildContext context) {
    return Column(
      children: [
      Seo.text(
          text: 'SEO html h1 Text',
          style: TextTagStyle.h1,
        child: Text('SEO show h1 Text 2')
      ),
        Seo.text(
            text: 'SEO html p Text',
            style: TextTagStyle.p,
            child: SelectableText('SEO show p Text 2')
        ),
    ]
    );
  }

**Comment by LucyJeong** [comment]
you should put code inside scaffold.
