### ISSUE TITLE
Feature request: add "rel" prop on link 

### ISSUE THREAD

**Issue by codakkk** [krokyze/flutter_seo#51]
There seems no way to specify "rel" prop. This is useful for various things, like "no follow link" and much more. Is it planned?

**Comment by krokyze** [comment]
Maybe I'm misunderstanding but LinkTag already has rel property. https://github.com/krokyze/flutter_seo/blob/1e95877324aae30f8c3939c1b3a79718717ad275/lib/head_tag.dart#L19

**Comment by codakkk** [comment]
> Maybe I'm misunderstanding but LinkTag already has rel property.
> 
> https://github.com/krokyze/flutter_seo/blob/1e95877324aae30f8c3939c1b3a79718717ad275/lib/head_tag.dart#L19

I'm talking about this prop:
`<a href="http://www.example.com" rel="nofollow">NoFollow Example</a>`

This is what I expect from a link widget

**Comment by krokyze** [comment]
@codakkk Hey, just released new 0.0.6 version with rel support added 😉
