### ISSUE TITLE
Seo Text Loading Before Website

### ISSUE THREAD

**Issue by izako666** [krokyze/flutter_seo#59]
Hi, I'm not sure if this is an actual issue or simply an error on my end, however, whenever I run my flutter web app, for at least a second before I see the actual website, I see the seo text that I had implemented.

Any Ideas?

**Comment by krokyze** [comment]
Hey I guess in Flutter you don't have background colour set for the whole app. Something like this: https://github.com/krokyze/flutter_seo/blob/b750190ab9465d7ab7edfeae81ce83bbf684304a/example/lib/main.dart#L23

**Comment by izako666** [comment]
Awesome! 
Thank you very much, and sorry for bothering you.

(Thank you for the package as well, you're doing great work.)
