### ISSUE TITLE
canonical showing up twice in the rendered HTML

### ISSUE THREAD

**Issue by jaredsburrows** [krokyze/flutter_seo#62]
When using `Seo.head`:
```
Seo.head(
  tags: <HeadTag>[
    MetaTag(
      name: 'description',
      content: toolInfo.pageDescription(context),
     ),
    LinkTag(
       rel: 'canonical',
      href: 'https://burrows.tools${toolInfo.routeName}',
    )
  ],
  child: toolInfo.toolRouteFactory(),
);
```

I am seeing the following in the rendered HTML:
`<link rel="canonical" href="https://burrows.tools">`
and
`<link rel="canonical" href="https://burrows.tools/json-formatter" flt-seo="">`

Is it just safe to remove the "default" HTML `<link rel="canonical" href="https://burrows.tools">`?

**Comment by krokyze** [comment]
Hey, yep you can remove the default html one 😉
