### ISSUE TITLE
Flutter WASM support?

### ISSUE THREAD

**Issue by ps6067966** [krokyze/flutter_seo#78]
It will be cool if its support wasm as per new flutter stable version 3.22.0

**Comment by nietsmmar** [comment]
Eagerly waiting for WASM support too!

**Comment by Bilonik** [comment]
Any ETA?

**Comment by krokyze** [comment]
Apologies for the long wait. I'll aim to have this done by the end of the month.

**Comment by krokyze** [comment]
Hey. Just letting you know, I've released new version 0.0.9 with wasm support.
